id: I2D8784DC
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:22:34.059571
last_modified: 2023-02-08 15:22:34.059688
source_metadata:
  title: Saddharmapuṇḍarīka
  language: zh
bases:
  3EDE:
    base_file: 3EDE.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
